services:
  cobalt_playlist:
    image: ghcr.io/hyperdefined/playlist.cobalt.directory:latest
    restart: unless-stopped
    container_name: cobalt_playlist
    environment:
      - COBALT_API_KEY=xxx
      - COBALT_API=https://cobalt-backend.canine.tools
      - PUBLIC_COBALT_API_DISPLAY=cobalt.canine.tools
    ports:
      - 127.0.0.1:3000:3000 # reverse proxy to port 3000, change the first port if it's taken
